-- Stores the Claude-written narrative review for each submission. Generated by
-- the `stack-review` edge function and surfaced on the report screen + retained
-- for sales follow-up.
alter table public.submissions add column if not exists ai_feedback text;
